baseURL = 'https://blog.oda.world'
languageCode = 'ja'
title = 'ODA WORLD'
theme = 'material-design'
publishDir = 'docs'
canonifyurls = true
hasCJKLanguage = true
googleAnalytics = 'G-93E1496REW'
copyright = "Â© 2021 ODA WORLD"

[params]
  twitter = "@oskfjzp"
  facebook = "last.pass.oda"
  github = "GOD-oda"

[markup]
  [markup.highlight]
    codeFences = true
    lineNoStart = 1
    lineNumbersInTable = true
    noClasses = true

